function dataR = realPointsI(data, mu, sigma)
    dataR = (diag((data - repmat(mu(1,:),size(data,1),1))*(data - repmat(mu(1,:),size(data,1),1))')  <= sigma(1,1)^2)...
          | (diag((data - repmat(mu(2,:),size(data,1),1))*(data - repmat(mu(2,:),size(data,1),1))')  <= sigma(1,1)^2)...
          | (diag((data - repmat(mu(3,:),size(data,1),1))*(data - repmat(mu(3,:),size(data,1),1))')  <= sigma(1,1)^2)...
          ;
end